# LLM Process

A notebook used to simplify (ie. remove columns from & restructure) the dataset for LLM processing

In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

## Setup

In [3]:
data_dir = "../raw"
filename = data_dir + "/merged_2021_2025.csv"
raw_df = df = pd.read_csv(filename, index_col=0, header=[0, 1], low_memory=False)

In [4]:
flat = raw_df.copy()
flat.columns = [f"{a.replace(' ', "_")}_{b.replace(' ', "_")}" for a, b in flat.columns]
flat.head()

,Time_Date,Time_Local_Time_Of_Day,Place_Locale_Reference,Place_State_Reference,Place_Relative_Position.Angle.Radial,Place_Relative_Position.Distance.Nautical_Miles,Place_Altitude.AGL.Single_Value,Place_Altitude.MSL.Single_Value,Place_Latitude_/_Longitude_(UAS),Environment_Flight_Conditions,...,Events_Detector,Events_When_Detected,Events_Result,Assessments_Contributing_Factors_/_Situations,Assessments_Primary_Problem,Report_1_Narrative,Report_1_Callback,Report_2_Narrative,Report_2_Callback,Report_1_Synopsis
2260174,202507,1201-1800,BWI.Airport,MD,NaN,NaN,NaN,900.0,NaN,VMC,...,Person Air Traffic Control,In-flight,General None Reported / Taken,Procedure; Human Factors; ATC Equipment / Nav ...,Ambiguous,Aircraft vectored in within 1NM to final appro...,NaN,NaN,NaN,Air carrier Captain reported a low altitude al...
2260249,202507,0601-1200,ZZZ.Airport,US,NaN,NaN,NaN,NaN,NaN,NaN,...,Automation Aircraft Other Automation; Person F...,In-flight,Flight Crew Executed Go Around / Missed Approa...,Human Factors; Aircraft,Ambiguous,While on short final we received a glideslope ...,NaN,NaN,NaN,Air carrier pilot reported receiving an aircra...
2260370,202507,1801-2400,ZZZ.ARTCC,US,NaN,NaN,NaN,35000.0,NaN,VMC,...,Person Flight Crew,In-flight,Air Traffic Control Issued New Clearance; Air ...,Aircraft,Aircraft,Flying at cruise; FL350; the FO was the PF and...,NaN,At cruise; FL350; during level-off; the Captai...,NaN,B737 flight crew reported observing a slowing ...
2261277,202507,1801-2400,ZZZ.Airport,US,NaN,2.6,160.0,NaN,NaN,NaN,...,Person Flight Crew,In-flight,General None Reported / Taken,Human Factors,Human Factors,On Day 0 around XA:30; I forgot to get LAANC a...,Reporter stated TRUST certificate was obtained...,NaN,NaN,Recreational / Hobbyist UAS pilot reported fly...
2261317,202507,NaN,ZZZ.Airport,US,NaN,NaN,NaN,9000.0,NaN,VMC,...,Automation Aircraft Other Automation; Person F...,In-flight,Flight Crew Became Reoriented; Flight Crew Reg...,Weather; Human Factors; Procedure,Procedure,Divert into ZZZ from ZZZ1. FO flying. Vectors ...,NaN,Extremely strong winds blew us off the LOC whi...,NaN,B737 flight crew reported the pilot flying in ...

In [27]:
# print(flat.iloc[0].to_json())
tt = flat[flat.Assessments_Primary_Problem == 'Human Factors']
with pd.option_context(
    "display.max_rows", None,
):  # more options can be specified also
    print(

    tt[[
        "Assessments_Primary_Problem",
        "Person_1_Human_Factors",
        # "Person_2_Human_Factors",
        # "",
    ]].map(lambda x : str(set(x.lower().split("; "))) if isinstance(x, str) else "NaN").value_counts()
    )

Assessments_Primary_Problem  Person_1_Human_Factors
{'human factors'}            {'situational awareness'}                                                                                                                                                       1043
                             {'situational awareness', 'communication breakdown'}                                                                                                                             819
                             {'communication breakdown'}                                                                                                                                                      812
                             NaN                                                                                                                                                                              790
                             {'situational awareness', 'training / qualification'}                                                                                                                            224
                             {'situational awareness', 'communication breakdown', 'confusion'}                                                                                                                189
                             {'situational awareness', 'communication breakdown', 'training / qualification'}                                                                                                 185
                             {'distraction', 'situational awareness'}                                                                                                                                         165
                             {'training / qualification'}                                                                                                                                                     157
                             {'workload', 'time pressure'}                                                                                                                                                    111
                             {'situational awareness', 'human-machine interface'}                                                                                                                              92
                             {'situational awareness', 'communication breakdown', 'time pressure'}                                                                                                             86
                             {'troubleshooting'}                                                                                                                                                               83
                             {'other / unknown'}                                                                                                                                                               80
                             {'situational awareness', 'confusion'}                                                                                                                                            78
                             {'situational awareness', 'time pressure'}                                                                                                                                        74
                             {'workload', 'communication breakdown', 'time pressure'}                                                                                                                          73
                             {'workload', 'troubleshooting', 'time pressure'}                                                                                                                                  69
                             {'distraction'}                                                                                                                                                                   64
                             {'time pressure'}                                                                                                                                                                 58
                             {'situational awareness', 'communication breakdown', 'human-machine interface'}                                                                                                   56
                             {'distraction', 'situational awareness', 'communication breakdown'}                                                                                                               53
                             {'communication breakdown', 'confusion'}                                                                                                                                          47
                             {'communication breakdown', 'time pressure'}                                                                                                                                      45
                             {'workload', 'situational awareness', 'time pressure'}                                                                                                                            44
                             {'workload'}                                                                                                                                                                      43
                             {'confusion'}                                                                                                                                                                     42
                             {'workload', 'situational awareness'}                                                                                                                                             41
                             {'workload', 'distraction', 'situational awareness'}                                                                                                                              39
                             {'workload', 'distraction', 'situational awareness', 'communication breakdown', 'time pressure'}                                                                                  39
                             {'workload', 'situational awareness', 'communication breakdown', 'time pressure'}                                                                                                 39
                             {'communication breakdown', 'training / qualification'}                                                                                                                           38
                             {'workload', 'troubleshooting'}                                                                                                                                                   38
                             {'human-machine interface'}                                                                                                                                                       36
                             {'workload', 'distraction', 'situational awareness', 'time pressure'}                                                                                                             36
                             {'situational awareness', 'communication breakdown', 'training / qualification', 'confusion'}                                                                                     35
                             {'distraction', 'situational awareness', 'confusion'}                                                                                                                             35
                             {'communication breakdown', 'other / unknown'}                                                                                                                                    35
                             {'distraction', 'situational awareness', 'communication breakdown', 'confusion'}                                                                                                  34
                             {'workload', 'distraction', 'time pressure'}                                                                                                                                      33
                             {'situational awareness', 'human-machine interface', 'confusion'}                                                                                                                 32
                             {'workload', 'situational awareness', 'communication breakdown'}                                                                                                                  30
                             {'workload', 'distraction', 'situational awareness', 'confusion'}                                                                                                                 29
                             {'workload', 'distraction', 'situational awareness', 'communication breakdown', 'confusion', 'time pressure'}                                                                     27
                             {'workload', 'communication breakdown'}                                                                                                                                           27
                             {'situational awareness', 'communication breakdown', 'human-machine interface', 'confusion'}                                                                                      27
                             {'distraction', 'communication breakdown'}                                                                                                                                        26
                             {'workload', 'distraction', 'situational awareness', 'communication breakdown'}                                                                                                   25
                             {'situational awareness', 'communication breakdown', 'time pressure', 'confusion'}                                                                                                25
                             {'distraction', 'situational awareness', 'training / qualification'}                                                                                                              25
                             {'workload', 'situational awareness', 'communication breakdown', 'confusion', 'time pressure'}                                                                                    25
                             {'distraction', 'situational awareness', 'communication breakdown', 'training / qualification'}                                                                                   24
                             {'situational awareness', 'fatigue'}                                                                                                                                              24
                             {'troubleshooting', 'communication breakdown'}                                                                                                                                    23
                             {'workload', 'distraction', 'situational awareness', 'confusion', 'time pressure'}                                                                                                23
                             {'workload', 'troubleshooting', 'communication breakdown', 'time pressure'}                                                                                                       22
                             {'distraction', 'situational awareness', 'time pressure'}                                                                                                                         21
                             {'human-machine interface', 'situational awareness', 'communication breakdown', 'confusion', 'troubleshooting'}                                                                   20
                             {'situational awareness', 'training / qualification', 'confusion'}                                                                                                                20
                             {'workload', 'distraction'}                                                                                                                                                       20
                             {'workload', 'distraction', 'communication breakdown', 'time pressure'}                                                                                                           19
                             {'workload', 'distraction', 'situational awareness', 'communication breakdown', 'time pressure', 'other / unknown'}                                                               19
                             {'workload', 'situational awareness', 'communication breakdown', 'confusion'}                                                                                                     18
                             {'situational awareness', 'troubleshooting'}                                                                                                                                      18
                             {'workload', 'situational awareness', 'communication breakdown', 'training / qualification'}                                                                                      16
                             {'training / qualification', 'situational awareness', 'communication breakdown', 'human-machine interface'}                                                                       14
                             {'workload', 'distraction', 'situational awareness', 'communication breakdown', 'confusion'}                                                                                      14
                             {'workload', 'distraction', 'time pressure', 'confusion'}                                                                                                                         14
                             {'situational awareness', 'other / unknown'}                                                                                                                                      14
                             {'troubleshooting', 'time pressure'}                                                                                                                                              14
                             {'workload', 'situational awareness', 'time pressure', 'confusion'}                                                                                                               13
                             {'training / qualification', 'situational awareness', 'human-machine interface'}                                                                                                  13
                             {'workload', 'troubleshooting', 'communication breakdown'}                                                                                                                        13
                             {'distraction', 'confusion'}                                                                                                                                                      12
                             {'communication breakdown', 'human-machine interface'}                                                                                                                            12
                             {'workload', 'situational awareness', 'confusion'}                                                                                                                                12
                             {'distraction', 'situational awareness', 'communication breakdown', 'time pressure'}                                                                                              12
                             {'distraction', 'situational awareness', 'human-machine interface'}                                                                                                               12
                             {'workload', 'distraction', 'situational awareness', 'training / qualification'}                                                                                                  12
                             {'workload', 'training / qualification'}                                                                                                                                          12
                             {'workload', 'situational awareness', 'communication breakdown', 'human-machine interface'}                                                                                       12
                             {'workload', 'distraction', 'communication breakdown'}                                                                                                                            12
                             {'situational awareness', 'communication breakdown', 'fatigue'}                                                                                                                   11
                             {'distraction', 'communication breakdown', 'time pressure'}                                                                                                                       11
                             {'distraction', 'situational awareness', 'communication breakdown', 'confusion', 'time pressure'}                                                                                 11
                             {'situational awareness', 'time pressure', 'confusion'}                                                                                                                           11
                             {'situational awareness', 'communication breakdown', 'human-machine interface', 'troubleshooting'}                                                                                11
                             {'workload', 'distraction', 'communication breakdown', 'confusion', 'time pressure'}                                                                                              11
                             {'workload', 'time pressure', 'other / unknown'}                                                                                                                                  11
                             {'situational awareness', 'troubleshooting', 'communication breakdown'}                                                                                                           10
                             {'troubleshooting', 'other / unknown'}                                                                                                                                            10
                             {'distraction', 'time pressure'}                                                                                                                                                  10
                             {'communication breakdown', 'time pressure', 'confusion'}                                                                                                                         10
                             {'workload', 'distraction', 'situational awareness', 'communication breakdown', 'confusion', 'time pressure', 'other / unknown'}                                                  10

In [6]:
narrative_only = flat[
    ["Assessments_Primary_Problem", "Report_1_Narrative", "Report_2_Narrative"]
]

### Cleaning Target & De-duplication
Here we examine if the target is NaN or dataset has any duplicates. Both Report_1_Narrative & Report_2_Narrative have duplicates (which shouldn't be the case).

In [15]:
narrative_only.info()

<class 'pandas.DataFrame'>
Index: 25526 entries, 2260174 to 2315041
Data columns (total 3 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Assessments_Primary_Problem  25089 non-null  str
 1   Report_1_Narrative           25526 non-null  str
 2   Report_2_Narrative           5389 non-null   str
dtypes: str(3)
memory usage: 797.7 KB

In [16]:
narrative_only.describe()

,Assessments_Primary_Problem,Report_1_Narrative,Report_2_Narrative
count,25089,25526,5389
unique,97,25522,5224
top,Human Factors,The UAS lost the telemetry link 1;300 feet fro...,[Report narrative contained no additional info...
freq,8370,3,125

In [17]:
# Identify Report 1 Narrative that are duplicated

r1_dupes = narrative_only[
    narrative_only.Report_1_Narrative.duplicated(keep=False)
]
r1_dupes.dropna(how="all")

,Assessments_Primary_Problem,Report_1_Narrative,Report_2_Narrative
2291690,Aircraft,On approach into ZZZ runway XXR; landing gear ...,After an otherwise uneventful flight; while on...
2014961,Aircraft,The UAS lost the telemetry link 1;300 feet fro...,NaN
2014962,Aircraft,The UAS lost the telemetry link 1;300 feet fro...,NaN
2014963,Aircraft,The UAS lost the telemetry link 1;300 feet fro...,NaN
2233790,Human Factors,In attempt to do my short field landing coming...,NaN
2242665,Ambiguous,In attempt to do my short field landing coming...,NaN
2303286,Aircraft,On approach into ZZZ runway XXR; landing gear ...,After an otherwise uneventful flight; while on...

In [25]:
r2_only = narrative_only.copy()
r2_dupes = r2_only[r2_only.Report_2_Narrative.duplicated(keep=False) & pd.notna(r2_only.Report_2_Narrative)]
r2_dupes.dropna(how="all")
display(r2_dupes.Report_2_Narrative.value_counts())
print("Sentinel values have lots of duplicates.")

Report_2_Narrative
[Report narrative contained no additional information.]    125
[Narrative contained no additional information.]            24
[Report narrative contained no additional information]      10
[Report narrative contained no additional information].      7
[Narrative added no additional information.]                 2
[Narrative contained no additional information]              2
[Report contained no additional information.]                2
Name: count, dtype: int64

Sentinel values have lots of duplicates.

In [26]:
# Find all occurrences of sentinel value string to ensure we don't delete actual data
# r2_no_sentinel = []
sentinel = "contained no additional information"
print("R1 Narrative w/ sentinels")
display(narrative_only[
    narrative_only.Report_1_Narrative.str.contains(sentinel)
])
print("R2 Narrative w/ sentinels")
display(narrative_only[narrative_only.Report_2_Narrative.str.contains(sentinel)][
    ["Report_2_Narrative"]
].value_counts())
print("So we can safely replace sentinel string w/ NaN & not delete real info.")

R1 Narrative w/ sentinels

Empty DataFrame
Columns: [Assessments_Primary_Problem, Report_1_Narrative, Report_2_Narrative]
Index: []

R2 Narrative w/ sentinels

Report_2_Narrative
[Report narrative contained no additional information.]    125
[Narrative contained no additional information.]            24
[Report narrative contained no additional information]      10
[Report narrative contained no additional information].      7
[Narrative contained no additional information]              2
[Report contained no additional information.]                2
Second narrative contained no additional information.        1
Name: count, dtype: int64

So we can safely replace sentinel string w/ NaN & not delete real info.

In [27]:
no_nan_r2_dupes = r2_dupes[~r2_dupes.Report_2_Narrative.str.contains(sentinel)]
no_nan_r2_dupes.sort_values(by="Report_2_Narrative").index

Index([1811991, 1851270], dtype='int64')

In [21]:
# Searching these indices on the DB, they indeed do NOT have a primary problem assigned.
prob_null = narrative_only[pd.isna(narrative_only.Assessments_Primary_Problem)]
prob_null

,Assessments_Primary_Problem,Report_1_Narrative,Report_2_Narrative
1780552,NaN,ZZZ1 went ATC zero due to a COVID cleaning aro...,NaN
1781139,NaN,At touchdown; aircraft started to pull right a...,NaN
1782360,NaN,I was the PM (Pilot Monitoring) and the CA (Ca...,NaN
1782374,NaN,On approach to Runway XX at ZZZ. Pilot flying ...,NaN
1785122,NaN,Was working these two sectors combined. It nee...,NaN
...,...,...,...
2312691,NaN,On Day 0; between XA30z -XC00z; operating as P...,NaN
2314212,NaN,Exiting the runway on EWR Runway 22R at night ...,NaN
2314249,NaN,On Day 0 we were given an IFR clearance from S...,On departure after climbing to 7.000 on the he...
2314640,NaN,Sent a CPDLC route change for direct IOW (Iowa...,While in Cruise in contact with Cleveland Cent...
2314789,NaN,While taxiing to 21R we were given taxi instru...,NaN

After referencing the DB, we can: 
1) Drop all items where the primary problem is NaN (since there is no label available)
2) Deduplicate & keep the first Report_1_Narrative (indeed, the narratives are exactly the same and in ONE case -- ACN 2233790/2242665 -- they have different primary problem labels)
3) Replace sentinel values (eg. "contained not additional info") with NaN
4) Apply Keep-first-override to all the duplicate Report_2_Narratives (see README) & null Report_1_Narratives

In [28]:
sentinel_substring = "contained no additional information"
sentinel_substring_2 = "narrative added no additional information"

def convert_sentinel(s:str):
    if not isinstance(s, str) or sentinel_substring in s.lower() or sentinel_substring_2 in s.lower():
        return np.nan
    
    return s


filtered = narrative_only[pd.notna(narrative_only.Assessments_Primary_Problem)].copy()
filtered = filtered.drop_duplicates(["Report_1_Narrative"], keep="first")
filtered["Report_2_Narrative"] = filtered.Report_2_Narrative.apply(convert_sentinel)

filtered.describe()

,Assessments_Primary_Problem,Report_1_Narrative,Report_2_Narrative
count,25085,25085,5125
unique,97,25085,5125
top,Human Factors,Aircraft vectored in within 1NM to final appro...,At cruise; FL350; during level-off; the Captai...
freq,8370,1,1

## Normalize Target
Now we make sure the Primary Problem is just one of the major categories (not subcategories).

In [29]:
category_counts = filtered.Assessments_Primary_Problem.value_counts()
print(category_counts.to_string())

Assessments_Primary_Problem
Human Factors                                                           8370
Aircraft                                                                8193
Procedure                                                               2410
Ambiguous                                                               1983
Weather                                                                  823
Airport                                                                  610
Environment - Non Weather Related                                        594
Chart Or Publication                                                     336
Airspace Structure                                                       322
ATC Equipment / Nav Facility / Buildings                                 316
Software and Automation                                                  169
Company Policy                                                           132
Equipment / Tooling                                                       96
Aircraft; Aircraft                                                        79
Aircraft; Human Factors                                                   64
MEL                                                                       59
Human Factors; Human Factors                                              57
Incorrect / Not Installed / Unavailable Part                              48
Human Factors; Aircraft                                                   48
Human Factors; Procedure                                                  34
Staffing                                                                  27
Manuals                                                                   25
Ambiguous; Aircraft                                                       22
Aircraft; Procedure                                                       19
Aircraft; Ambiguous                                                       19
Procedure; Aircraft                                                       14
Ambiguous; Human Factors                                                  14
Procedure; Human Factors                                                  13
Human Factors; Ambiguous                                                  12
Airport; Human Factors                                                     9
Environment - Non Weather Related; Human Factors                           9
Procedure; Procedure                                                       8
Ambiguous; Procedure                                                       8
Aircraft; ATC Equipment / Nav Facility / Buildings                         6
Ambiguous; Ambiguous                                                       6
Airport; Procedure                                                         6
Human Factors; Weather                                                     6
Logbook Entry                                                              5
Aircraft; Airport                                                          5
Aircraft; Weather                                                          5
Environment - Non Weather Related; Aircraft                                4
Human Factors; ATC Equipment / Nav Facility / Buildings                    4
Weather; Aircraft                                                          4
Weather; Human Factors                                                     4
ATC Equipment / Nav Facility / Buildings; Human Factors                    4
Airport; Aircraft                                                          4
Ambiguous; Airport                                                         4
ATC Equipment / Nav Facility / Buildings; Ambiguous                        3
Environment - Non Weather Related; Procedure                               3
Aircraft; Chart Or Publication                                             3
Ambiguous; Airspace Structure                                              3
Aircraft; MEL                                                              3
Environment - Non Weather Related; Ambiguous                               3
Weather; Ambiguous                                                         3
Ambiguous; Weather                                                         2
Human Factors; Chart Or Publication                                        2
Procedure; Airspace Structure                                              2
Chart Or Publication; Aircraft                                             2
Ambiguous; Chart Or Publication                                            2
Airspace Structure; Aircraft                                               2
Procedure; Weather                                                         2
ATC Equipment / Nav Facility / Buildings; Aircraft                         2
Human Factors; Airport                                                     2
Aircraft; Environment - Non Weather Related                                2
Aircraft; Airspace Structure                                               2
ATC Equipment / Nav Facility / Buildings; Airspace Structure               2
Weather; Staffing                                                          1
Software and Automation; Human Factors                                     1
Environment - Non Weather Related; Environment - Non Weather Related       1
Airspace Structure; Human Factors                                          1
Procedure; ATC Equipment / Nav Facility / Buildings                        1
Company Policy; Ambiguous                                                  1
Ambiguous; Company Policy                                                  1
Airport; Ambiguous                                                         1
Weather; Airport                                                           1
Equipment / Tooling; Human Factors                                         1
Procedure; Chart Or Publication                                            1
Procedure; Environment - Non Weather Related                               1
Weather; Company Policy                                                    1
Chart Or Publication; Environment - Non Weather Related                    1
Human Factors; Airspace Structure                                          1
Procedure; Software and Automation                                         1
Airport; Software and Automation                                           1
Chart Or Publication; Ambiguous                                            1
Human Factors; Manuals                                                     1
Airport; Weather                                                           1
Airspace Structure; Airport                                                1
Weather; Procedure                                                         1
Software and Automation; Ambiguous                                         1
Ambiguous; Environment - Non Weather Related                               1
ATC Equipment / Nav Facility / Buildings; Procedure                        1
Chart Or Publication; Airspace Structure                                   1
Airport; Environment - Non Weather Related                                 1
Procedure; Ambiguous                                                       1
Human Factors; Environment - Non Weather Related                           1
Airspace Structure; Ambiguous                                              1
Procedure; Airport                                                         1

In [30]:
s = 0
for c, r in zip(category_counts.index, category_counts):
    li = c.replace(" ", "").split(";") #bc sometimes we have things like 'aircraft; aircraft'
    if len(set(li)) > 1:
        s+= r
    
print(s, "records are a multi-class target")
print(round(s / category_counts.sum(), 4), "of all records")

416 records are a multi-class target
0.0166 of all records

In [31]:
def setify(x:str):
    return set(x.lower().replace(" ", "").split(";"))


processed = filtered.copy()
processed["setify"] = processed.Assessments_Primary_Problem.apply(setify)
processed['is_multi'] = processed.setify.apply(lambda x : len(x) > 1)
processed = processed[~processed.is_multi]
processed["Assessments_Primary_Problem"] = processed.setify.apply(lambda x : list(x)[0])

display(processed.Assessments_Primary_Problem.value_counts())
processed.drop(['setify', 'is_multi'], axis=1, inplace=True)
processed.head()

Assessments_Primary_Problem
humanfactors                              8427
aircraft                                  8272
procedure                                 2418
ambiguous                                 1989
weather                                    823
airport                                    610
environment-nonweatherrelated              595
chartorpublication                         336
airspacestructure                          322
atcequipment/navfacility/buildings         316
softwareandautomation                      169
companypolicy                              132
equipment/tooling                           96
mel                                         59
incorrect/notinstalled/unavailablepart      48
staffing                                    27
manuals                                     25
logbookentry                                 5
Name: count, dtype: int64

,Assessments_Primary_Problem,Report_1_Narrative,Report_2_Narrative
2260174,ambiguous,Aircraft vectored in within 1NM to final appro...,NaN
2260249,ambiguous,While on short final we received a glideslope ...,NaN
2260370,aircraft,Flying at cruise; FL350; the FO was the PF and...,At cruise; FL350; during level-off; the Captai...
2261277,humanfactors,On Day 0 around XA:30; I forgot to get LAANC a...,NaN
2261317,procedure,Divert into ZZZ from ZZZ1. FO flying. Vectors ...,Extremely strong winds blew us off the LOC whi...

In [32]:
processed.to_csv("narratives.csv")

In [ ]:
# Count tokens, roughly
processed.Report_1_Narrative.apply(lambda x: x.count(" ")).sum()

np.int64(4843308)