Comparing the diversity of narrative reports for reports with the same event tags to assess inter-rater reliability

In [31]:
import pandas as pd
import numpy as np

from datasets import load_dataset

from huggingface_hub import hf_hub_download

import utils

In [32]:
events_df = pd.read_csv("../data-processing/events.csv")
events_df.rename(columns={"Unnamed: 0" : "acn"}, inplace=True)
#events_df.set_index("acn", inplace=True)

combined_events_df = events_df[events_df.columns[:1]]

# Remove NaN instances from set
combined_events_df["temp"] = events_df[events_df.columns[2:]].agg(set, axis=1)
for index, row in combined_events_df.iterrows():
    no_nan_list = []
    for event in row["temp"]: 
        if isinstance(event, str): no_nan_list.append(event)
    combined_events_df.at[index, "temp"] = no_nan_list

combined_events_df

# Converted to a string because strings can be hashed, which is useful for finding duplicates
combined_events_df["events"] = [", ".join(r["temp"]) for i, r in combined_events_df.iterrows()]
combined_events_df.drop(columns="temp", inplace=True)
combined_events_df

/tmp/ipykernel_10692/3739016954.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_events_df["temp"] = events_df[events_df.columns[2:]].agg(set, axis=1)
/tmp/ipykernel_10692/3739016954.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_events_df["events"] = [", ".join(r["temp"]) for i, r in combined_events_df.iterrows()]
/tmp/ipykernel_10692/3739016954.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_events_df.drop(columns="temp", inplace=True)

           acn                                             events
0      2260174  anomaly_inflight_event_/_encounter_unstabilize...
1      2260249  detector_person_flight_crew, result_flight_cre...
2      2260370  detector_person_flight_crew, result_air_traffi...
3      2261277  anomaly_deviation_/_discrepancy_-_procedural_u...
4      2261317  anomaly_deviation_-_track_/_heading_all_types,...
...        ...                                                ...
24529  2314733  anomaly_aircraft_equipment_problem_critical, a...
24530  2314971  anomaly_deviation_/_discrepancy_-_procedural_u...
24531  2314972  anomaly_deviation_/_discrepancy_-_procedural_f...
24532  2314978  anomaly_ground_event_/_encounter_ground_strike...
24533  2315041  anomaly_deviation_-_track_/_heading_all_types,...

[24534 rows x 2 columns]

In [33]:
narratives_df = pd.read_csv("../data-processing/narratives.csv")
narratives_df.rename(columns={"Unnamed: 0" : "acn"}, inplace=True)
narratives_df.set_index("acn", inplace=True)

narratives_df.head()

,Assessments_Primary_Problem,Report_1_Narrative,Report_2_Narrative
acn,,,
2260174,ambiguous,Aircraft vectored in within 1NM to final appro...,NaN
2260249,ambiguous,While on short final we received a glideslope ...,NaN
2260370,aircraft,Flying at cruise; FL350; the FO was the PF and...,At cruise; FL350; during level-off; the Captai...
2261277,humanfactors,On Day 0 around XA:30; I forgot to get LAANC a...,NaN
2261317,procedure,Divert into ZZZ from ZZZ1. FO flying. Vectors ...,Extremely strong winds blew us off the LOC whi...

In [34]:
# Group by the same events string, and then turn those ACNs into lists
duplicates_series = combined_events_df.groupby("events")["acn"].apply(list)
duplicates_series

for index, acns in duplicates_series.items():
    if len(acns) <= 1:          # Not a duplicate
        duplicates_series.drop(index, inplace=True)

duplicates_series

events
anomaly_aircraft_equipment_problem_critical                                                                                                                                                                      [2032791, 2260241, 2261197, 2264946, 2270182, ...
anomaly_aircraft_equipment_problem_critical, anomaly_deviation_/_discrepancy_-_procedural_clearance                                                                                                                  [2285608, 2296521, 2298943, 2304776, 2314733]
anomaly_aircraft_equipment_problem_critical, anomaly_deviation_/_discrepancy_-_procedural_far, anomaly_deviation_/_discrepancy_-_procedural_published_material_/_policy                                                                         [2265523, 2299417]
anomaly_aircraft_equipment_problem_critical, anomaly_deviation_/_discrepancy_-_procedural_far, anomaly_deviation_/_discrepancy_-_procedural_published_material_/_policy, result_general_none_reported_/_taken                                   [1842997, 2147798]
anomaly_aircraft_equipment_problem_critical, anomaly_deviation_/_discrepancy_-_procedural_maintenance, anomaly_deviation_/_discrepancy_-_procedural_far                                                                                [2260914, 2282617, 2287520]
                                                                                                                                                                                                                                       ...
when_detected_taxi, detector_person_ground_personnel, anomaly_critical, anomaly_conflict_ground_conflict, anomaly_ground_event_/_encounter_other_/_unknown                                                                                      [1800549, 1860625]
when_detected_taxi, result_flight_crew_took_evasive_action, detector_person_ground_personnel, anomaly_critical, anomaly_conflict_ground_conflict                                                                 [1780620, 1844526, 2118890, 2146196, 2148210, ...
when_detected_taxi, result_flight_crew_took_evasive_action, detector_person_ground_personnel, anomaly_critical, anomaly_conflict_ground_conflict, anomaly_ground_event_/_encounter_other_/_unknown                                              [2105102, 2232214]
when_detected_taxi, result_general_none_reported_/_taken, detector_person_ground_personnel, anomaly_critical, anomaly_conflict_ground_conflict                                                                       [1803246, 1822583, 2006084, 2088200, 2252836]
when_detected_taxi, result_general_none_reported_/_taken, detector_person_ground_personnel, anomaly_critical, anomaly_conflict_ground_conflict, anomaly_ground_event_/_encounter_other_/_unknown                                                [1908124, 2185341]
Name: acn, Length: 1993, dtype: object

In [35]:

for index, acns in duplicates_series.items():
    primary_problem = events_df[events_df["acn"] == acns[0]]["assessments_primary_problem"].item()

    for acn in acns[1:]:
        if events_df[events_df["acn"] == acn]["assessments_primary_problem"].item() == primary_problem:
            duplicates_series[index].remove(acn)
    
    # If every other acn had the same primary problem, remove from duplicates
    if len(duplicates_series[index]) <= 1:
        duplicates_series.drop(index, inplace=True)

### Analysis

In [52]:
def printDuplicateNarratives(index : int):
    print()

    print("Event Tags:")
    tags = duplicates_series.index[index].split(", ")    
    for t in tags:
        print('\t', t)

    print()

    for i in range(len(duplicates_series.iloc[index])):
        acn = duplicates_series.iloc[index][i]
        primary_problem = events_df[events_df["acn"] == acn]["assessments_primary_problem"].item()
        

        print(f"===== Narrative {i} =====")
        print("Primary Problem:", primary_problem)
        print("ACN:", acn)
        print(narratives_df.at[acn, "Report_1_Narrative"])
        print()

In [56]:
len(duplicates_series)

832

In [ ]:
# Note: if you're using VS Code like I am, you can turn on word wrapping in settings under notebook.output.wordWrap

# Potentially Interesting Indices: 10, 100

printDuplicateNarratives(1)

Event Tags:
	 anomaly_aircraft_equipment_problem_critical

===== Narrative 0 =====
Primary Problem: aircraft
ACN: 2032791
During takeoff phase engine failure.

===== Narrative 1 =====
Primary Problem: environment___non_weather_related
ACN: 2260241
During climb while passing through 27000 climbing to FL400. We encountered wake turbulence from Aircraft Y initially and it rolled the aircraft 30 degrees to the right. As we uprighted the aircraft we encountered wake turbulence again with the same roll to the right. We decreased pitch and the right turn took us 15-20 degrees to the right. I advised NY center of our deviation and about the turn to the right. ATC said we couldn't deviate right and to turn left of course. I complied with their statement and turned left to accomplish a left offset of the allowed 3 miles until at FL380 the on course to PSB. NY center controller had possibly understood we purposely turned to the right and subsequently encroached another sector. During wake turbulence TCAS was on; referenced; no traffic observed; no TA or RA event occurred. Referencing Longitude AOM turbulence in the caution section we followed company procedure of advising ATC of any deviation.

===== Narrative 2 =====
Primary Problem: weather
ACN: 2285797
At approximately 50 feet AGL over the runway threshold crew encountered wake turbulence; presumably from the A320 that landed prior. Aircraft rolled uncommanded to approximately 45 Angle of Bank (AOB) as crew lost aileron authority. Crew immediately executed a go-around and regained control authority of the aircraft within five seconds as the aircraft began climbing and accelerating. Crew then returned for an uneventful full-stop. No crew or passengers were injured throughout the course of events.Cause: Wake turbulence from preceding A320; specifically wingtip vortices greater than the wingspan of the aircraft.Suggestions: Greater spacing from preceding aircraft on approach.

===== Narrative 3 =====
Primary Problem: procedure
ACN: 2289069
Practice approach was approved under VFR for ZZZ ILS XXR entire procedure we were flying Aircraft X for a training flight conducted under Part 91 and commenced the approach we were also cleared to fly the published missed approach procedure issued for that sector. We were handed off to ZZZ tower and after establishing comms we were 'cleared for the option XXR' the IAP was flown to DA (Decision Altitude) minimums and the missed approach procedure was commenced. At the proper altitude we began the right turn on heading after reaching appropriate altitude which is approximately midfield for our type aircraft. This put us on a 010 heading from the runway. Aircraft Y appeared to be doing practice landings and pattern work in right traffic flying at TPA (Traffic Pattern Altitude). The NMAC event happened at midfield right traffic as we were climbing out to 2000 and the other aircraft was approaching midfield in right traffic. No special instructions by ATC issued for either aircraft. Prior to NMAC ZZZ Tower ordered Aircraft X on frequency to turn left to avoid traffic conflict. Provided that we were given the full procedure and routing of the missed approach path and missed approach this traffic conflict was very likely to happen when done in conjunction with VFR traffic in right pattern for XXR or XXL at ZZZ.